export const attendanceData = {
  2024: {
    January: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    February: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    March: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    April: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    May: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    June: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    July: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    August: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    September: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    October: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    November: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
    December: [
      { name: "ASI(M) Sir", completed: true },
      { name: "SI(M) Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
    ],
  },
  2025: {
    January: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    February: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    March: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    April: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    May: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    June: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    July: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    August: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    September: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    October: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    November: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
    December: [
      { name: "ASI(M) Sir", completed: false },
      { name: "SI(M) Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
    ],
  },
};
