export const billData = {
  2024: {
    January: [
      { name: "ASIM Sir", completed: true },
      { name: "SIM Sir", completed: true },
      { name: "F&AO Sir", completed: true },
      { name: "CFO(F/P) Sir", completed: true },
      { name: "CFO(T) Sir", completed: true },
      { name: "CFO(O) Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    February: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    March: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    April: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    May: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    June: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    July: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: true },
      { name: "Treasury", completed: true },
      { name: "Vendor", completed: true },
      { name: "Man Power", completed: true },
    ],
    August: [
      { name: "Pawan Gupta Sir", completed: true },
      { name: "Vinod Kumar Dixit Sir", completed: true },
      { name: "Shashi Kala Verma", completed: true },
      { name: "Animesh Sir", completed: true },
      { name: "Arun Kumar Sir", completed: true },
      { name: "Vijay Kumar Sir", completed: true },
      { name: "ADG Fire Sir", completed: true },
      { name: "DG Fire Sir", completed: true },
      { name: "ASIM Sir", completed: true },
      { name: "Account Section", completed: true },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    September: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    October: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    November: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    December: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
  },
  2025: {
    January: [
      { name: "ASIM Sir", completed: false },
      { name: "SIM Sir", completed: false },
      { name: "F&AO Sir", completed: false },
      { name: "CFO(F/P) Sir", completed: false },
      { name: "CFO(T) Sir", completed: false },
      { name: "CFO(O) Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    February: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    March: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    April: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    May: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    June: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    July: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    August: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    September: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    October: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    November: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
    December: [
      { name: "Pawan Gupta Sir", completed: false },
      { name: "Vinod Kumar Dixit Sir", completed: false },
      { name: "Shashi Kala Verma", completed: false },
      { name: "Animesh Sir", completed: false },
      { name: "Arun Kumar Sir", completed: false },
      { name: "Vijay Kumar Sir", completed: false },
      { name: "ADG Fire Sir", completed: false },
      { name: "DG Fire Sir", completed: false },
      { name: "ASIM Sir", completed: false },
      { name: "Account Section", completed: false },
      { name: "DDO Sir", completed: false },
      { name: "Treasury", completed: false },
      { name: "Vendor", completed: false },
      { name: "Man Power", completed: false },
    ],
  },
};
